/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Gnarly Docs ⌐◨-◨",
  "tagline": "Onboarding Docs for Gnars Community. Gnars are a new way to fund extreme athletes using web3 tools",
  "url": "https://sktbrd.github.io",
  "baseUrl": "/gnars-docs/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "trailingSlash": false,
  "organizationName": "sktbrd",
  "projectName": "gnars-docs",
  "deploymentBranch": "gh-pages",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "fr",
      "pt-br",
      "es"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/web3warrior/Documents/code/gnars-docs/gnars-docs-git/gnars-docs/sidebars.js",
          "editUrl": "https://github.com/sktbrd/gnars-docs/tree/main/"
        },
        "blog": {
          "showReadingTime": false,
          "editUrl": "https://github.com/sktbrd/gnars-docs/tree/main/"
        },
        "theme": {
          "customCss": "/Users/web3warrior/Documents/code/gnars-docs/gnars-docs-git/gnars-docs/src/css/custom.css"
        }
      }
    ]
  ],
  "themes": [
    [
      "/Users/web3warrior/Documents/code/gnars-docs/gnars-docs-git/gnars-docs/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "Gnars",
      "logo": {
        "alt": "GNARS logo",
        "src": "img/favicon.ico"
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro",
          "position": "left",
          "label": "Tutorials"
        },
        {
          "href": "https://github.com/sktbrd/gnars-docs",
          "label": "GitHub",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "type": "dropdown",
          "label": "Projects",
          "position": "left",
          "items": [
            {
              "label": "ThatsGnarly",
              "href": "https://thatsgnar.ly"
            },
            {
              "label": "Skatehive",
              "href": "https://skatehive.app"
            },
            {
              "label": "Alps DAO",
              "href": "https://opensea.io/collection/gnars-v2"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Get a Gnar NFT",
          "position": "left",
          "items": [
            {
              "label": "Auctions",
              "href": "https://gnars.wtf"
            },
            {
              "label": "OpenSea",
              "href": "https://opensea.io/collection/gnars-v2"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Games",
          "position": "left",
          "items": [
            {
              "label": "Quest For Stoken",
              "href": "https://stoken.quest/"
            },
            {
              "label": "Grinderz",
              "href": "https://gnars.fun/"
            }
          ]
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Tutorial",
              "to": "/docs/intro"
            },
            {
              "label": "Charmverse",
              "href": "https://app.charmverse.io/share/gnars/page-9870330106092746"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "href": "https://discord.gg/gnars"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/gnarsdao"
            },
            {
              "label": "Snapshot",
              "href": "https://snapshot.org/#/gnars.eth"
            }
          ]
        },
        {
          "title": "Shred to Earn",
          "items": [
            {
              "label": "🛹 Skatehive App",
              "href": "https://skatehive.app"
            },
            {
              "label": "🌊 Surfhive App",
              "href": "https://peakd.com/c/hive-141964/created"
            },
            {
              "label": "🤘 Thats Gnarly",
              "href": "https://thatsgnar.ly"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/sktbrd/gnars-docs"
            }
          ]
        }
      ],
      "copyright": "Copyright © is a lie. Built with Weed"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
